import err;

let multiply :: proc => [a: Integer, factor: Integer] {
 return a * factor;
};


let a :: multiply(10, 2);

let main() ~ Int :: begin
 let panic :: proc => [_: err.Error] {
  throw("Panic!");
 }
 assert(a, 20).error.map(panic);
end