import err, assert;

let multiply :: proc => (a: Integer, factor: Integer) {
 return a * factor;
};

let a :: multiply(10, 2);

let main() ~ Int :: begin
 let panic :: proc => (_: Error) {
  @throw("Panic!");
 };

 assert.eq(20, a).map_err(panic);
end